#!/usr/bin/perl
use strict;
use Net::IP::Match;

while (<>) {
  chomp($_);
  if (m|.*\s(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})(?:\s+(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}))?\s.*| ) {
    if ( defined $2 and $2 ne '') {
      print "$1 $2\n";
    } else {
      print "$1\n";
    }
  }
}
